use_frameworks!

platform :ios, '8.0'

target 'MyGybPodsSpec_First_Example' do
  pod 'MyGybPodsSpec_First', :path => '../'

  target 'MyGybPodsSpec_First_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
